
server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
spring:
  

  datasource:
    url: jdbc:postgresql://localhost:5432/enoca_ecommerce
    username: enocaUser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true


  
      

  
   
